In [9]:
import numpy as np
a = np.array([[1,1],[4,3]])
a

array([[1, 1],
       [4, 3]])

In [10]:

b = np.array([5,15])
b

array([ 5, 15])

In [11]:

a_inv = np.linalg.inv(a)
a_inv

array([[-3.,  1.],
       [ 4., -1.]])

In [12]:

print(np.dot(a_inv,b))

[0. 5.]


# 0-D Array

In [14]:
import numpy as np
a = np.array(4)
print(a)
print(a.ndim)

4
0


# 1-d tensor


In [16]:
a = np.array([1,2,3]) # also called as vector
print(a)
print(a.ndim)

[1 2 3]
1


# 2-D tensor(metrices)

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


# Rank,Axes and shape
- Number of axes = Rank --> Number of dimensions
- shape - Number of rows* number of columns