In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
df.iloc[:,1:]

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995       0       0       0       0       0       0       0       0       0   
41996       0       0       0       0       0       0       0       0       0   
41997       0       0       0       0       0       0       0       0       0   
41998       0       0       0       0       0       0       0       0       0   
41999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 784 columns]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [7]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [8]:
clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [9]:
y_pred1 = clf1.predict(x_test)
y_pred2 = clf2.predict(x_test)

In [10]:
from  sklearn.metrics import accuracy_score
print('Accuracy Score of Logistic Regression',accuracy_score(y_test,y_pred1))
print('Accuracy Score of Decision Tree',accuracy_score(y_test,y_pred2))

Accuracy Score of Logistic Regression 0.9153571428571429
Accuracy Score of Decision Tree 0.854047619047619


In [13]:
from sklearn.metrics import confusion_matrix
print('Confusion Matrix of Logistic Regression\n')
print(confusion_matrix(y_test,y_pred1))

Confusion Matrix of Logistic Regression

[[789   0   1   4   3   2   8   2   2   2]
 [  0 916   4   4   4   3   2   2  10   4]
 [  6   6 755  13  10   2   8  12  27   4]
 [  3   2  19 765   1  30   0   8  15   8]
 [  1   4   4   0 755   4   7   7   9  22]
 [ 10   0   5  32   3 671  14   4  19  13]
 [  8   2  13   2   9  10 806   1   6   0]
 [  0   5  11   4  11   1   3 829   4  44]
 [  3  15   7  22   1  31   7   4 715  10]
 [  4   6   7  10  20   9   0  28   4 688]]


In [14]:
print('Confusion Matrix of Decision Tree\n')
print(confusion_matrix(y_test,y_pred2))

Confusion Matrix of Decision Tree

[[735   1  10   6   8  12  17   6   8  10]
 [  2 893  10   5   7   8   2   3  14   5]
 [ 16  13 681  33  13  12  25  19  20  11]
 [  5   9  19 712   6  36   5  12  29  18]
 [  4   7  12   8 691   9  11  12  24  35]
 [ 12   3   5  49  11 609  22  11  30  19]
 [ 16   4  14   5  10  22 758   3  16   9]
 [  4   7  22  19   7   3   4 812   8  26]
 [ 11   9  21  36  15  24  16  12 648  23]
 [ 12   9   9  19  35   9   5  27  16 635]]


In [15]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [19]:
print('For Logistic Regression Model')
print(precision_score(y_test,y_pred1,average=None))

For Logistic Regression Model
[0.95752427 0.958159   0.91404358 0.89369159 0.92411261 0.87942333
 0.94269006 0.92419175 0.88162762 0.86540881]


In [20]:
print(recall_score(y_test,y_pred1,average='macro'))

0.9142597055013422


In [21]:
print(f1_score(y_test,y_pred1,average='weighted'))

0.9153192919147192


In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.97      0.96       813
           1       0.96      0.97      0.96       949
           2       0.91      0.90      0.90       843
           3       0.89      0.90      0.90       851
           4       0.92      0.93      0.93       813
           5       0.88      0.87      0.87       771
           6       0.94      0.94      0.94       857
           7       0.92      0.91      0.92       912
           8       0.88      0.88      0.88       815
           9       0.87      0.89      0.88       776

    accuracy                           0.92      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.92      0.92      0.92      8400

